{% set name = "stix2-patterns" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 07750c5a5af2c758e9d2aa4dde9d8e04bcd162ac2a9b0b4c4de4481d443efa08

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - antlr4-python3-runtime ~=4.9.0
    - pip
    - python >=3.8
    - six
    - wheel
    - setuptools
  run:
    - antlr4-python3-runtime ~=4.9.0
    - python >=3.8
    - six

test:
  imports:
    - stix2patterns
    - stix2patterns.grammars
    - stix2patterns.test
    - stix2patterns.test.v20
    - stix2patterns.test.v21
    - stix2patterns.v20
    - stix2patterns.v20.grammars
    - stix2patterns.v21
    - stix2patterns.v21.grammars
  requires:
    - pip
    - coverage
    - pytest
    - pytest-cov
  commands:
    - pip check
    - validate-patterns --help

about:
  home: "https://github.com/oasis-open/cti-pattern-validator"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Validate STIX 2 Patterns."
  doc_url: https://stix2-patterns.readthedocs.io/en/latest/
  dev_url: https://github.com/oasis-open/cti-pattern-validator

extra:
  recipe-maintainers:
    - your-github-id-here
